import clr

clr.AddReference("StockSharp.Messages")
clr.AddReference("StockSharp.Algo")

from System import TimeSpan
from StockSharp.Messages import DataType, CandleStates
from StockSharp.Algo.Indicators import SimpleMovingAverage, WeightedMovingAverage, DecimalIndicatorValue
from StockSharp.Algo.Strategies import Strategy

class center_of_gravity_candle_strategy(Strategy):
    """
    Trades synthetic candles generated by Center of Gravity calculation.
    Uses SMA and LWMA averages smoothed to create synthetic OHLC, then trades color changes.
    """

    def __init__(self):
        super(center_of_gravity_candle_strategy, self).__init__()
        self._candle_type = self.Param("CandleType", DataType.TimeFrame(TimeSpan.FromMinutes(5))) \
            .SetDisplay("Candle Type", "Timeframe", "General")
        self._period = self.Param("Period", 10) \
            .SetDisplay("CoG Period", "Center of gravity period", "Indicator")
        self._smooth_period = self.Param("SmoothPeriod", 1) \
            .SetDisplay("Smooth Period", "Smoothing period", "Indicator")

        self._prev_color = 0
        self._has_prev = False

        self._open_sma = None
        self._high_sma = None
        self._low_sma = None
        self._close_sma = None
        self._open_lwma = None
        self._high_lwma = None
        self._low_lwma = None
        self._close_lwma = None
        self._open_smooth = None
        self._high_smooth = None
        self._low_smooth = None
        self._close_smooth = None

    @property
    def candle_type(self):
        return self._candle_type.Value

    def OnReseted(self):
        super(center_of_gravity_candle_strategy, self).OnReseted()
        self._prev_color = 0
        self._has_prev = False
        self._open_sma = None
        self._high_sma = None
        self._low_sma = None
        self._close_sma = None
        self._open_lwma = None
        self._high_lwma = None
        self._low_lwma = None
        self._close_lwma = None
        self._open_smooth = None
        self._high_smooth = None
        self._low_smooth = None
        self._close_smooth = None

    def OnStarted(self, time):
        super(center_of_gravity_candle_strategy, self).OnStarted(time)

        length = self._period.Value
        s_len = self._smooth_period.Value

        self._open_sma = SimpleMovingAverage()
        self._open_sma.Length = length
        self._high_sma = SimpleMovingAverage()
        self._high_sma.Length = length
        self._low_sma = SimpleMovingAverage()
        self._low_sma.Length = length
        self._close_sma = SimpleMovingAverage()
        self._close_sma.Length = length

        self._open_lwma = WeightedMovingAverage()
        self._open_lwma.Length = length
        self._high_lwma = WeightedMovingAverage()
        self._high_lwma.Length = length
        self._low_lwma = WeightedMovingAverage()
        self._low_lwma.Length = length
        self._close_lwma = WeightedMovingAverage()
        self._close_lwma.Length = length

        self._open_smooth = SimpleMovingAverage()
        self._open_smooth.Length = s_len
        self._high_smooth = SimpleMovingAverage()
        self._high_smooth.Length = s_len
        self._low_smooth = SimpleMovingAverage()
        self._low_smooth.Length = s_len
        self._close_smooth = SimpleMovingAverage()
        self._close_smooth.Length = s_len

        self._prev_color = 0
        self._has_prev = False

        subscription = self.SubscribeCandles(self.candle_type)
        subscription.Bind(self.on_process).Start()

        area = self.CreateChartArea()
        if area is not None:
            self.DrawCandles(area, subscription)
            self.DrawOwnTrades(area)

    def on_process(self, candle):
        if candle.State != CandleStates.Finished:
            return

        t = candle.OpenTime

        def _proc(ind, val):
            inp = DecimalIndicatorValue(ind, val, t)
            inp.IsFinal = True
            return ind.Process(inp)

        o_sma = _proc(self._open_sma, candle.OpenPrice)
        o_lwma = _proc(self._open_lwma, candle.OpenPrice)
        h_sma = _proc(self._high_sma, candle.HighPrice)
        h_lwma = _proc(self._high_lwma, candle.HighPrice)
        l_sma = _proc(self._low_sma, candle.LowPrice)
        l_lwma = _proc(self._low_lwma, candle.LowPrice)
        c_sma = _proc(self._close_sma, candle.ClosePrice)
        c_lwma = _proc(self._close_lwma, candle.ClosePrice)

        if (not self._open_sma.IsFormed or not self._open_lwma.IsFormed or
            not self._high_sma.IsFormed or not self._high_lwma.IsFormed or
            not self._low_sma.IsFormed or not self._low_lwma.IsFormed or
            not self._close_sma.IsFormed or not self._close_lwma.IsFormed):
            return

        open_prod = (float(o_sma) + float(o_lwma)) / 2.0
        high_prod = (float(h_sma) + float(h_lwma)) / 2.0
        low_prod = (float(l_sma) + float(l_lwma)) / 2.0
        close_prod = (float(c_sma) + float(c_lwma)) / 2.0

        o_smooth = _proc(self._open_smooth, open_prod)
        h_smooth = _proc(self._high_smooth, high_prod)
        l_smooth = _proc(self._low_smooth, low_prod)
        c_smooth = _proc(self._close_smooth, close_prod)

        if (not self._open_smooth.IsFormed or not self._high_smooth.IsFormed or
            not self._low_smooth.IsFormed or not self._close_smooth.IsFormed):
            return

        open_val = float(o_smooth)
        close_val = float(c_smooth)

        if open_val < close_val:
            color = 1
        elif open_val > close_val:
            color = -1
        else:
            color = 0

        if self._has_prev:
            if color == 1 and self._prev_color != 1 and self.Position <= 0:
                self.BuyMarket()
            elif color == -1 and self._prev_color != -1 and self.Position >= 0:
                self.SellMarket()

        self._prev_color = color
        self._has_prev = True

    def CreateClone(self):
        return center_of_gravity_candle_strategy()
