using System.Collections.Immutable;
using System.IO;
using System.Linq;
using System.Text;

using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;

namespace Tests.SourceGen;

[Generator(LanguageNames.CSharp)]
public class StrategyTestGenerator : IIncrementalGenerator
{
	// Test method names (derived from folder) with manually-defined tests in Overrides files
	private static readonly System.Collections.Generic.HashSet<string> _overrides = new(System.StringComparer.Ordinal)
	{
		"Ch2010Structure",
		"CointegrationPairs",
		"DeltaNeutralArbitrage",
		"DispersionTrading",
		"ImproveMaRsiHedge",
		"MulticurrencyOverlayHedge",
		"Pairs",
		"PairsTrading",
		"SpotFuturesArbitrage",
		"Spreader2",
		"StatisticalArbitrage",
	};

	public void Initialize(IncrementalGeneratorInitializationContext context)
	{
		// C# tests: scan Strategy subclasses
		var classes = context.SyntaxProvider
			.CreateSyntaxProvider(
				predicate: static (node, _) => node is ClassDeclarationSyntax cds
					&& cds.BaseList != null
					&& cds.Modifiers.Any(m => m.Text == "public")
					&& !cds.Modifiers.Any(m => m.Text == "abstract"),
				transform: static (ctx, ct) =>
				{
					var cds = (ClassDeclarationSyntax)ctx.Node;
					var symbol = ctx.SemanticModel.GetDeclaredSymbol(cds, ct) as INamedTypeSymbol;
					if (symbol == null)
						return null;

					if (!InheritsFromStrategy(symbol))
						return null;

					var filePath = ctx.Node.SyntaxTree.FilePath.Replace('\\', '/');
					var methodName = FolderToMethodName(filePath);
					if (methodName == null)
						return null;

					return methodName + "|" + symbol.Name;
				})
			.Where(static x => x != null);

		var collected = classes.Collect();

		context.RegisterSourceOutput(collected, static (spc, items) =>
		{
			if (items.IsEmpty)
				return;

			var entries = items
				.Select(x => { var parts = x.Split('|'); return (methodName: parts[0], className: parts[1]); })
				.OrderBy(x => x.methodName)
				.ToList();

			var sb = new StringBuilder();

			sb.AppendLine("// <auto-generated/>");
			sb.AppendLine();
			sb.AppendLine("using System.Threading.Tasks;");
			sb.AppendLine("using Microsoft.VisualStudio.TestTools.UnitTesting;");
			sb.AppendLine("using StockSharp.Samples.Strategies;");
			sb.AppendLine();
			sb.AppendLine("namespace StockSharp.Tests;");
			sb.AppendLine();
			sb.AppendLine("partial class CSharpTests");
			sb.AppendLine("{");

			var usedNames = new System.Collections.Generic.HashSet<string>();

			foreach (var (methodName, className) in entries)
			{
				var uniqueName = methodName;
				var i = 2;
				while (!usedNames.Add(uniqueName))
					uniqueName = methodName + i++;

				if (_overrides.Contains(uniqueName))
					continue;

				sb.AppendLine($"\t[TestMethod]");
				sb.AppendLine($"\tpublic Task {uniqueName}()");
				sb.AppendLine($"\t\t=> RunStrategy<{className}>();");
				sb.AppendLine();
			}

			sb.AppendLine("}");

			spc.AddSource("CSharpTests.g.cs", sb.ToString());
		});

		// Python tests: scan .py AdditionalFiles
		var pyFiles = context.AdditionalTextsProvider
			.Where(static f => f.Path.EndsWith(".py"));

		var pyCollected = pyFiles.Collect();

		context.RegisterSourceOutput(pyCollected, static (spc, files) =>
		{
			if (files.IsEmpty)
				return;

			var entries = new System.Collections.Generic.List<(string methodName, string relPath)>();

			foreach (var file in files)
			{
				var path = file.Path.Replace('\\', '/');

				// extract part after /API/ — e.g. "0001_MA_CrossOver/PY/ma_crossover_strategy.py"
				var apiIdx = path.IndexOf("/API/");
				if (apiIdx < 0)
					continue;

				var relPath = path.Substring(apiIdx + "/API/".Length);

				var methodName = FolderToMethodName(path);
				if (methodName == null)
					continue;

				entries.Add((methodName, relPath));
			}

			if (entries.Count == 0)
				return;

			entries.Sort((a, b) => string.CompareOrdinal(a.relPath, b.relPath));

			var sb = new StringBuilder();

			sb.AppendLine("// <auto-generated/>");
			sb.AppendLine();
			sb.AppendLine("using System.Threading.Tasks;");
			sb.AppendLine("using Microsoft.VisualStudio.TestTools.UnitTesting;");
			sb.AppendLine();
			sb.AppendLine("namespace StockSharp.Tests;");
			sb.AppendLine();
			sb.AppendLine("partial class PythonTests");
			sb.AppendLine("{");

			var usedNames = new System.Collections.Generic.HashSet<string>();

			foreach (var (methodName, relPath) in entries)
			{
				var uniqueName = methodName;
				var i = 2;
				while (!usedNames.Add(uniqueName))
					uniqueName = methodName + i++;

				if (_overrides.Contains(uniqueName))
					continue;

				sb.AppendLine($"\t[TestMethod]");
				sb.AppendLine($"\tpublic Task {uniqueName}()");
				sb.AppendLine($"\t\t=> RunStrategy(\"{relPath}\");");
				sb.AppendLine();
			}

			sb.AppendLine("}");

			spc.AddSource("PythonTests.g.cs", sb.ToString());
		});
	}

	/// <summary>
	/// Extract folder name from a full file path under API/ and convert to PascalCase method name.
	/// E.g. ".../API/0256_Bollinger_Band_Width_Breakout/CS/SomeStrategy.cs" → "BollingerBandWidthBreakout"
	/// </summary>
	private static string FolderToMethodName(string filePath)
	{
		var idx = filePath.IndexOf("/API/");
		if (idx < 0)
			return null;

		var afterApi = filePath.Substring(idx + "/API/".Length);
		var slashIdx = afterApi.IndexOf('/');
		if (slashIdx < 0)
			return null;

		var folderName = afterApi.Substring(0, slashIdx);

		// Remove numeric prefix: "0256_Bollinger_Band_Width_Breakout" → "Bollinger_Band_Width_Breakout"
		var underscoreIdx = folderName.IndexOf('_');
		if (underscoreIdx >= 0 && int.TryParse(folderName.Substring(0, underscoreIdx), out _))
			folderName = folderName.Substring(underscoreIdx + 1);

		var result = SnakeToPascal(folderName, null);

		// C# identifiers can't start with a digit
		if (result.Length > 0 && char.IsDigit(result[0]))
			result = "_" + result;

		return result;
	}

	private static string SnakeToPascal(string snake, string removeSuffix)
	{
		if (removeSuffix != null && snake.EndsWith(removeSuffix))
			snake = snake.Substring(0, snake.Length - removeSuffix.Length);

		var sb = new StringBuilder();
		var upper = true;

		foreach (var c in snake)
		{
			if (c == '_' || c == '-')
			{
				upper = true;
				continue;
			}

			sb.Append(upper ? char.ToUpperInvariant(c) : char.ToLowerInvariant(c));
			upper = false;
		}

		return sb.ToString();
	}

	private static bool InheritsFromStrategy(INamedTypeSymbol symbol)
	{
		var baseType = symbol.BaseType;
		while (baseType != null)
		{
			if (baseType.Name == "Strategy"
				&& baseType.ContainingNamespace?.ToDisplayString() == "StockSharp.Algo.Strategies")
				return true;

			baseType = baseType.BaseType;
		}

		return false;
	}
}
