using System.Collections.Immutable;
using System.Linq;
using System.Text;

using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;

namespace Tests.SourceGen;

[Generator(LanguageNames.CSharp)]
public class StrategyTestGenerator : IIncrementalGenerator
{
	public void Initialize(IncrementalGeneratorInitializationContext context)
	{
		var classes = context.SyntaxProvider
			.CreateSyntaxProvider(
				predicate: static (node, _) => node is ClassDeclarationSyntax cds
					&& cds.BaseList != null
					&& cds.Modifiers.Any(m => m.Text == "public")
					&& !cds.Modifiers.Any(m => m.Text == "abstract"),
				transform: static (ctx, ct) =>
				{
					var cds = (ClassDeclarationSyntax)ctx.Node;
					var symbol = ctx.SemanticModel.GetDeclaredSymbol(cds, ct) as INamedTypeSymbol;
					if (symbol == null)
						return null;

					if (!InheritsFromStrategy(symbol))
						return null;

					return symbol.Name;
				})
			.Where(static name => name != null);

		var collected = classes.Collect();

		context.RegisterSourceOutput(collected, static (spc, names) =>
		{
			if (names.IsEmpty)
				return;

			var sorted = names.Distinct().OrderBy(n => n).ToList();
			var sb = new StringBuilder();

			sb.AppendLine("// <auto-generated/>");
			sb.AppendLine();
			sb.AppendLine("using System.Threading.Tasks;");
			sb.AppendLine("using Microsoft.VisualStudio.TestTools.UnitTesting;");
			sb.AppendLine();
			sb.AppendLine("namespace StockSharp.Tests;");
			sb.AppendLine();
			sb.AppendLine("partial class CSharpTests");
			sb.AppendLine("{");

			foreach (var className in sorted)
			{
				var methodName = className.EndsWith("Strategy")
					? className.Substring(0, className.Length - "Strategy".Length)
					: className;

				sb.AppendLine($"\t[TestMethod]");
				sb.AppendLine($"\tpublic Task {methodName}()");
				sb.AppendLine($"\t\t=> RunStrategy<{className}>();");
				sb.AppendLine();
			}

			sb.AppendLine("}");

			spc.AddSource("CSharpTests.g.cs", sb.ToString());
		});
	}

	private static bool InheritsFromStrategy(INamedTypeSymbol symbol)
	{
		var baseType = symbol.BaseType;
		while (baseType != null)
		{
			if (baseType.Name == "Strategy"
				&& baseType.ContainingNamespace?.ToDisplayString() == "StockSharp.Algo.Strategies")
				return true;

			baseType = baseType.BaseType;
		}

		return false;
	}
}
