using System.Collections.Immutable;
using System.IO;
using System.Linq;
using System.Text;

using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;

namespace Tests.SourceGen;

[Generator(LanguageNames.CSharp)]
public class StrategyTestGenerator : IIncrementalGenerator
{
	// Strategies with manually-defined tests in CSharpTests.Overrides.cs (need multi-instrument setup)
	private static readonly System.Collections.Generic.HashSet<string> _csOverrides = new(System.StringComparer.Ordinal)
	{
		"Ch2010StructureStrategy",
		"CointegrationPairsStrategy",
		"DeltaNeutralArbitrageStrategy",
		"ImproveMaRsiHedgeStrategy",
		"PairsStrategy",
		"PairsTradingStrategy",
		"SpotFuturesArbitrageStrategy",
		"Spreader2Strategy",
		"StatisticalArbitrageStrategy",
	};

	// Python test method names with manually-defined tests in PythonTests.Overrides.cs
	private static readonly System.Collections.Generic.HashSet<string> _pyOverrides = new(System.StringComparer.Ordinal)
	{
		"Ch2010Structure",
		"CointegrationPairs",
		"DeltaNeutralArbitrage",
		"Pairs",
		"PairsTrading",
		"SpotFuturesArbitrage",
		"StatisticalArbitrage",
	};

	public void Initialize(IncrementalGeneratorInitializationContext context)
	{
		// C# tests: scan Strategy subclasses
		var classes = context.SyntaxProvider
			.CreateSyntaxProvider(
				predicate: static (node, _) => node is ClassDeclarationSyntax cds
					&& cds.BaseList != null
					&& cds.Modifiers.Any(m => m.Text == "public")
					&& !cds.Modifiers.Any(m => m.Text == "abstract"),
				transform: static (ctx, ct) =>
				{
					var cds = (ClassDeclarationSyntax)ctx.Node;
					var symbol = ctx.SemanticModel.GetDeclaredSymbol(cds, ct) as INamedTypeSymbol;
					if (symbol == null)
						return null;

					if (!InheritsFromStrategy(symbol))
						return null;

					return symbol.Name;
				})
			.Where(static name => name != null);

		var collected = classes.Collect();

		context.RegisterSourceOutput(collected, static (spc, names) =>
		{
			if (names.IsEmpty)
				return;

			var sorted = names.Distinct().OrderBy(n => n).ToList();
			var sb = new StringBuilder();

			sb.AppendLine("// <auto-generated/>");
			sb.AppendLine();
			sb.AppendLine("using System.Threading.Tasks;");
			sb.AppendLine("using Microsoft.VisualStudio.TestTools.UnitTesting;");
			sb.AppendLine("using StockSharp.Samples.Strategies;");
			sb.AppendLine();
			sb.AppendLine("namespace StockSharp.Tests;");
			sb.AppendLine();
			sb.AppendLine("partial class CSharpTests");
			sb.AppendLine("{");

			foreach (var className in sorted)
			{
				if (_csOverrides.Contains(className))
					continue;

				var methodName = className.EndsWith("Strategy")
					? className.Substring(0, className.Length - "Strategy".Length)
					: className;

				sb.AppendLine($"\t[TestMethod]");
				sb.AppendLine($"\tpublic Task {methodName}()");
				sb.AppendLine($"\t\t=> RunStrategy<{className}>();");
				sb.AppendLine();
			}

			sb.AppendLine("}");

			spc.AddSource("CSharpTests.g.cs", sb.ToString());
		});

		// Python tests: scan .py AdditionalFiles
		var pyFiles = context.AdditionalTextsProvider
			.Where(static f => f.Path.EndsWith(".py"));

		var pyCollected = pyFiles.Collect();

		context.RegisterSourceOutput(pyCollected, static (spc, files) =>
		{
			if (files.IsEmpty)
				return;

			var entries = new System.Collections.Generic.List<(string methodName, string relPath)>();

			foreach (var file in files)
			{
				var path = file.Path.Replace('\\', '/');

				// extract part after /API/ — e.g. "0001_MA_CrossOver/PY/ma_crossover_strategy.py"
				var apiIdx = path.IndexOf("/API/");
				if (apiIdx < 0)
					continue;

				var relPath = path.Substring(apiIdx + "/API/".Length);

				var fileName = Path.GetFileNameWithoutExtension(path);
				var methodName = SnakeToPascal(fileName, "_strategy");

				entries.Add((methodName, relPath));
			}

			if (entries.Count == 0)
				return;

			entries.Sort((a, b) => string.CompareOrdinal(a.relPath, b.relPath));

			var sb = new StringBuilder();

			sb.AppendLine("// <auto-generated/>");
			sb.AppendLine();
			sb.AppendLine("using System.Threading.Tasks;");
			sb.AppendLine("using Microsoft.VisualStudio.TestTools.UnitTesting;");
			sb.AppendLine();
			sb.AppendLine("namespace StockSharp.Tests;");
			sb.AppendLine();
			sb.AppendLine("partial class PythonTests");
			sb.AppendLine("{");

			var usedNames = new System.Collections.Generic.HashSet<string>();

			foreach (var (methodName, relPath) in entries)
			{
				var uniqueName = methodName;
				var i = 2;
				while (!usedNames.Add(uniqueName))
					uniqueName = methodName + i++;

				if (_pyOverrides.Contains(uniqueName))
					continue;

				sb.AppendLine($"\t[TestMethod]");
				sb.AppendLine($"\tpublic Task {uniqueName}()");
				sb.AppendLine($"\t\t=> RunStrategy(\"{relPath}\");");
				sb.AppendLine();
			}

			sb.AppendLine("}");

			spc.AddSource("PythonTests.g.cs", sb.ToString());
		});
	}

	private static string SnakeToPascal(string snake, string removeSuffix)
	{
		if (removeSuffix != null && snake.EndsWith(removeSuffix))
			snake = snake.Substring(0, snake.Length - removeSuffix.Length);

		var sb = new StringBuilder();
		var upper = true;

		foreach (var c in snake)
		{
			if (c == '_')
			{
				upper = true;
				continue;
			}

			sb.Append(upper ? char.ToUpperInvariant(c) : c);
			upper = false;
		}

		return sb.ToString();
	}

	private static bool InheritsFromStrategy(INamedTypeSymbol symbol)
	{
		var baseType = symbol.BaseType;
		while (baseType != null)
		{
			if (baseType.Name == "Strategy"
				&& baseType.ContainingNamespace?.ToDisplayString() == "StockSharp.Algo.Strategies")
				return true;

			baseType = baseType.BaseType;
		}

		return false;
	}
}
