using System.Collections.Immutable;
using System.IO;
using System.Linq;
using System.Text;

using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;

namespace Tests.SourceGen;

[Generator(LanguageNames.CSharp)]
public class StrategyTestGenerator : IIncrementalGenerator
{
	// Keep this bucket count in sync with the eight direct category jobs in .github/workflows/dotnet.yml.
	private const int _shardCount = 8;

	// Test method names (derived from folder) with manually-defined tests in Overrides files
	private static readonly System.Collections.Generic.HashSet<string> _overrides = new(System.StringComparer.Ordinal)
	{
		"BreakoutBarsTrend",
		"Ch2010Structure",
		"CointegrationPairs",
		"DeltaNeutralArbitrage",
		"DispersionTrading",
		"ImproveMaRsiHedge",
		"KeltnerSeasonalFilter",
		"MulticurrencyOverlayHedge",
		"Pairs",
		"PairsTrading",
		"SpotFuturesArbitrage",
		"Spreader2",
		"StatisticalArbitrage",
	};

	public void Initialize(IncrementalGeneratorInitializationContext context)
	{
		// C# tests: scan Strategy subclasses
		var classes = context.SyntaxProvider
			.CreateSyntaxProvider(
				predicate: static (node, _) => node is ClassDeclarationSyntax cds
					&& cds.BaseList != null
					&& cds.Modifiers.Any(m => m.Text == "public")
					&& !cds.Modifiers.Any(m => m.Text == "abstract"),
				transform: static (ctx, ct) =>
				{
					var cds = (ClassDeclarationSyntax)ctx.Node;
					var symbol = ctx.SemanticModel.GetDeclaredSymbol(cds, ct) as INamedTypeSymbol;
					if (symbol == null)
						return null;

					if (!InheritsFromStrategy(symbol))
						return null;

					var filePath = ctx.Node.SyntaxTree.FilePath.Replace('\\', '/');
					var strategyInfo = GetStrategyInfo(filePath);
					if (strategyInfo == null)
						return null;

					return strategyInfo.Value.methodName + "|" + symbol.Name + "|" + strategyInfo.Value.shard;
				})
			.Where(static x => x != null);

		var collected = classes.Collect();

		context.RegisterSourceOutput(collected, static (spc, items) =>
		{
			if (items.IsEmpty)
				return;

			var entries = items
				.Select(x => { var parts = x.Split('|'); return (methodName: parts[0], className: parts[1], shard: int.Parse(parts[2])); })
				.OrderBy(x => x.methodName)
				.ToList();

			var sb = new StringBuilder();

			sb.AppendLine("// <auto-generated/>");
			sb.AppendLine();
			sb.AppendLine("using System.Threading.Tasks;");
			sb.AppendLine("using Microsoft.VisualStudio.TestTools.UnitTesting;");
			sb.AppendLine("using StockSharp.Samples.Strategies;");
			sb.AppendLine();
			sb.AppendLine("namespace StockSharp.Tests;");
			sb.AppendLine();
			sb.AppendLine("partial class CSharpTests");
			sb.AppendLine("{");

			var usedNames = new System.Collections.Generic.HashSet<string>();

			foreach (var (methodName, className, shard) in entries)
			{
				var uniqueName = methodName;
				var i = 2;
				while (!usedNames.Add(uniqueName))
					uniqueName = methodName + i++;

				if (_overrides.Contains(uniqueName))
					continue;

				sb.AppendLine($"\t[TestMethod]");
				sb.AppendLine($"\t[TestCategory(\"Shard{shard:D2}\")]");
				sb.AppendLine($"\tpublic Task {uniqueName}()");
				sb.AppendLine($"\t\t=> RunStrategy<{className}>();");
				sb.AppendLine();
			}

			sb.AppendLine("}");

			spc.AddSource("CSharpTests.g.cs", sb.ToString());
		});

		// Python tests: scan .py AdditionalFiles
		var pyFiles = context.AdditionalTextsProvider
			.Where(static f => f.Path.EndsWith(".py"));

		var pyCollected = pyFiles.Collect();

		context.RegisterSourceOutput(pyCollected, static (spc, files) =>
		{
			if (files.IsEmpty)
				return;

			var entries = new System.Collections.Generic.List<(string methodName, string relPath, int shard)>();

			foreach (var file in files)
			{
				var path = file.Path.Replace('\\', '/');

				// Extract the path below API, including its numeric range directory.
				var apiIdx = path.IndexOf("/API/");
				if (apiIdx < 0)
					continue;

				var relPath = path.Substring(apiIdx + "/API/".Length);

				var strategyInfo = GetStrategyInfo(path);
				if (strategyInfo == null)
					continue;

				entries.Add((strategyInfo.Value.methodName, relPath, strategyInfo.Value.shard));
			}

			if (entries.Count == 0)
				return;

			entries.Sort((a, b) => string.CompareOrdinal(a.relPath, b.relPath));

			var sb = new StringBuilder();

			sb.AppendLine("// <auto-generated/>");
			sb.AppendLine();
			sb.AppendLine("using System.Threading.Tasks;");
			sb.AppendLine("using Microsoft.VisualStudio.TestTools.UnitTesting;");
			sb.AppendLine();
			sb.AppendLine("namespace StockSharp.Tests;");
			sb.AppendLine();
			sb.AppendLine("partial class PythonTests");
			sb.AppendLine("{");

			var usedNames = new System.Collections.Generic.HashSet<string>();

			foreach (var (methodName, relPath, shard) in entries)
			{
				var uniqueName = methodName;
				var i = 2;
				while (!usedNames.Add(uniqueName))
					uniqueName = methodName + i++;

				if (_overrides.Contains(uniqueName))
					continue;

				sb.AppendLine($"\t[TestMethod]");
				sb.AppendLine($"\t[TestCategory(\"Shard{shard:D2}\")]");
				sb.AppendLine($"\tpublic Task {uniqueName}()");
				sb.AppendLine($"\t\t=> RunStrategy(\"{relPath}\");");
				sb.AppendLine();
			}

			sb.AppendLine("}");

			spc.AddSource("PythonTests.g.cs", sb.ToString());
		});
	}

	/// <summary>
	/// Extract the numeric-prefixed strategy folder from a full file path under API/
	/// and convert it to a PascalCase method name. The strategy may be placed directly
	/// below API or below a numeric range directory such as 0201-0300.
	/// E.g. ".../API/0201-0300/0256_Bollinger_Band_Width_Breakout/CS/SomeStrategy.cs"
	/// becomes "BollingerBandWidthBreakout".
	/// </summary>
	private static (string methodName, int shard)? GetStrategyInfo(string filePath)
	{
		var idx = filePath.IndexOf("/API/");
		if (idx < 0)
			return null;

		var afterApi = filePath.Substring(idx + "/API/".Length);
		string folderName = null;
		var strategyId = 0;

		foreach (var segment in afterApi.Split('/'))
		{
			var underscoreIdx = segment.IndexOf('_');
			if (underscoreIdx <= 0 || !int.TryParse(segment.Substring(0, underscoreIdx), out strategyId))
				continue;

			folderName = segment.Substring(underscoreIdx + 1);
			break;
		}

		if (folderName == null)
			return null;

		var result = SnakeToPascal(folderName, null);

		// C# identifiers can't start with a digit
		if (result.Length > 0 && char.IsDigit(result[0]))
			result = "_" + result;

		return (result, strategyId % _shardCount);
	}

	private static string SnakeToPascal(string snake, string removeSuffix)
	{
		if (removeSuffix != null && snake.EndsWith(removeSuffix))
			snake = snake.Substring(0, snake.Length - removeSuffix.Length);

		var sb = new StringBuilder();
		var upper = true;

		foreach (var c in snake)
		{
			if (c == '_' || c == '-')
			{
				upper = true;
				continue;
			}

			sb.Append(upper ? char.ToUpperInvariant(c) : char.ToLowerInvariant(c));
			upper = false;
		}

		return sb.ToString();
	}

	private static bool InheritsFromStrategy(INamedTypeSymbol symbol)
	{
		var baseType = symbol.BaseType;
		while (baseType != null)
		{
			if (baseType.Name == "Strategy"
				&& baseType.ContainingNamespace?.ToDisplayString() == "StockSharp.Algo.Strategies")
				return true;

			baseType = baseType.BaseType;
		}

		return false;
	}
}
